//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Channel
    {
        public int ChannelID { get; set; }
        public string CID { get; set; }
        public string ChannelName { get; set; }
        public string ChannelEName { get; set; }
        public Nullable<int> PCID { get; set; }
        public Nullable<int> IsOutChannel { get; set; }
        public string OutChannelUrl { get; set; }
        public Nullable<int> Sorc { get; set; }
        public string BindDomain { get; set; }
        public string Review { get; set; }
        public Nullable<int> IsDel { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
    }
}
