//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Class
    {
        public C_Class()
        {
            this.C_News = new HashSet<C_News>();
        }
    
        public int ClassID { get; set; }
        public string CID { get; set; }
        public string ClassName { get; set; }
        public string ClassEName { get; set; }
        public int PCID { get; set; }
        public Nullable<int> IsOutClass { get; set; }
        public string OutClassUrl { get; set; }
        public Nullable<int> Sort { get; set; }
        public string BindDomain { get; set; }
        public string ClassModel { get; set; }
        public string Saveurl { get; set; }
        public string ClassFile { get; set; }
        public string Review { get; set; }
        public string Namerules { get; set; }
        public string PageIndex { get; set; }
        public string NewsSaveurl { get; set; }
        public string NewsLookName { get; set; }
        public string ImageUploadurl { get; set; }
        public Nullable<System.DateTime> PublicTime { get; set; }
        public string ClassDataTable { get; set; }
        public int ChannelID { get; set; }
        public string IsMenuShow { get; set; }
        public string MenuImage { get; set; }
        public string MenuTitle { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
        public string SCFileEXT { get; set; }
        public Nullable<int> IsLock { get; set; }
        public Nullable<int> IsDel { get; set; }
        public Nullable<int> CustomCode { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> IsPage { get; set; }
        public Nullable<int> IsHtml { get; set; }
    
        public virtual ICollection<C_News> C_News { get; set; }
    }
}
