//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionRulesTab
    {
        public int Id { get; set; }
        public string CollectionName { get; set; }
        public string SourceSiteTag { get; set; }
        public string SourceSiteName { get; set; }
        public string BaseUrl { get; set; }
        public string CollectionListRulesBig { get; set; }
        public string CollectionListRulesMin { get; set; }
        public string CollectionUrl { get; set; }
        public string Contentleft { get; set; }
        public string Contentright { get; set; }
        public string Titleleft { get; set; }
        public string Titleright { get; set; }
        public string Imgleft { get; set; }
        public string Imgright { get; set; }
        public string NewPublishTimeLeft { get; set; }
        public string NewPublishTimeRight { get; set; }
        public string TypeNameLeft { get; set; }
        public string TypeNameRight { get; set; }
        public string Encoding { get; set; }
        public Nullable<int> IsDel { get; set; }
    }
}
