//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public int LoginLogID { get; set; }
        public System.DateTime AddDate { get; set; }
        public int Manager_Id { get; set; }
        public string Manager_CName { get; set; }
        public string Ip { get; set; }
        public string Notes { get; set; }
        public Nullable<int> IsDel { get; set; }
        public string City { get; set; }
    }
}
