//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int MID { get; set; }
        public string LoginName { get; set; }
        public string LoginPass { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public string LoginIp { get; set; }
        public int LoginCount { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int Branch_Id { get; set; }
        public string Branch_Code { get; set; }
        public string Branch_Name { get; set; }
        public int Position_Id { get; set; }
        public string Position_Name { get; set; }
        public byte Enable { get; set; }
        public string CName { get; set; }
        public string EName { get; set; }
        public string PhotoImg { get; set; }
        public string Sex { get; set; }
        public string Birthday { get; set; }
        public string NativePlace { get; set; }
        public string NationalName { get; set; }
        public string Record { get; set; }
        public string GraduateCollege { get; set; }
        public string GraduateSpecialty { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Qq { get; set; }
        public string Msn { get; set; }
        public string Address { get; set; }
        public string Content { get; set; }
        public int Manager_Id { get; set; }
        public string Manager_CName { get; set; }
        public Nullable<int> IsDel { get; set; }
    }
}
