//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebConfig
    {
        public int WCID { get; set; }
        public string WebName { get; set; }
        public string WebDomain { get; set; }
        public string WebEmail { get; set; }
        public int LoginLogReserveTime { get; set; }
        public int UseLogReserveTime { get; set; }
        public string EmailSmtp { get; set; }
        public string EmailUserName { get; set; }
        public string EmailPassWord { get; set; }
        public string EmailDomain { get; set; }
        public Nullable<int> IsDel { get; set; }
    }
}
