//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSendHistory
    {
        public int Id { get; set; }
        public int SendUsers_Id { get; set; }
        public string SendUsers_Name { get; set; }
        public string SendUsers_Email { get; set; }
        public int RecUsers_Id { get; set; }
        public string RecUsers_Name { get; set; }
        public string RecUsers_Email { get; set; }
        public int RecUserLevel_Id { get; set; }
        public string RecUserLevel_Name { get; set; }
        public string EmailSubject { get; set; }
        public string EmailContent { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<byte> Status { get; set; }
        public string StatusName { get; set; }
        public string ErrorMsg { get; set; }
        public Nullable<int> Template_Id { get; set; }
        public string Template_Name { get; set; }
        public Nullable<int> IsDel { get; set; }
    }
}
