//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> ErrTime { get; set; }
        public string BrowserVersion { get; set; }
        public string BrowserType { get; set; }
        public string Ip { get; set; }
        public string PageUrl { get; set; }
        public string ErrMessage { get; set; }
        public string ErrSource { get; set; }
        public string StackTrace { get; set; }
        public string HelpLink { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<int> IsDel { get; set; }
    }
}
