//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterData
    {
        public int ID { get; set; }
        public string TableName { get; set; }
        public int DataID { get; set; }
        public int CreaterRoleID { get; set; }
        public int CreaterID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> ManagerID { get; set; }
    }
}
