//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagePowerSignPublic
    {
        public PagePowerSignPublic()
        {
            this.PagePowerSigns = new HashSet<PagePowerSign>();
        }
    
        public int PPSPID { get; set; }
        public string CName { get; set; }
        public string EName { get; set; }
        public string StyleClass { get; set; }
        public string Type { get; set; }
        public Nullable<int> IsDel { get; set; }
    
        public virtual ICollection<PagePowerSign> PagePowerSigns { get; set; }
    }
}
