//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagePowerSign
    {
        public int PPSID { get; set; }
        public Nullable<int> MIID { get; set; }
        public Nullable<int> PPSPID { get; set; }
        public string CName { get; set; }
        public string EName { get; set; }
    
        public virtual MenuInfo MenuInfo { get; set; }
        public virtual PagePowerSignPublic PagePowerSignPublic { get; set; }
    }
}
